### ISSUE TITLE
añadir SSD m.2 Lear 620 2tb

### ISSUE THREAD

**Issue by badaxavi** [AuxXxilium/arc-a#80]
Buenos días,
 Tengo un disco ssd m.2 NVMe Lexar 620 de 2tb y me gustaría poderlo utilizar en la instalación de arc a o cualquier otra instalación, ahora no lo reconoce. Hay alguna forma de que lo reconozca?

Saludos

**Comment by AuxXxilium** [comment]
First: Write english please
Second: You know that DSM doesn't support NVMe only Systems? DSM need a sata/sas disk for installation.

Except SA6400 with NVMeSystem Addon. But to use this you have to use arc and not arc-a or arc-c.
